# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{oink}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Noah Davis", "Bryan Helmkamp"]
  s.date = %q{2009-08-06}
  s.email = ["noahd1@yahoo.com", "bryan@brynary.com"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "README.rdoc",
     "Rakefile",
     "lib/stats.rb",
     "lib/stats/broadcaster.rb",
     "lib/stats/measure.rb",
     "lib/stats/memory_usage.rb",
     "lib/stats/middleware.rb",
     "lib/stats/rails/active_record_extensions.rb",
     "lib/stats/rails/cache_extensions.rb",
     "lib/stats/rails/sql_extensions.rb",
     "spec/fixtures/abstract_adapter.rb",
     "spec/fixtures/active_record.rb",
     "spec/fixtures/memcached.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/stats/rails_spec.rb",
     "spec/stats_spec.rb"
  ]
  s.homepage = %q{http://github.com/noahd1/oink}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Collect metrics from your production app to analyze later}
  s.test_files = [
    "spec/fixtures/abstract_adapter.rb",
     "spec/fixtures/active_record.rb",
     "spec/fixtures/memcached.rb",
     "spec/spec_helper.rb",
     "spec/stats/rails_spec.rb",
     "spec/stats_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
